### ISSUE TITLE
Copy text from host to TigerVNC is hanged

### ISSUE THREAD

**Issue by wmh** [TigerVNC/tigervnc#1045]
**Describe the bug**
Copy text is hanged in normal process.

**To Reproduce**
1. Go to 'Host'
2. Copy any text by select text and press 'Ctrl-C'
3. Go to 'TigerVNC', focus on any text input field
4. Press 'Ctrl-V' and it looks like hanged
5. Go to 'Host' and copy text again
6. Go to 'TigerVNC', focus on the text field, and the copy/paste is suddenly completed!!!

**Expected behavior**
I can complete the copy/paste process in step 4, instead of Step 6

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS: Ubuntu 20.04
 - VNC client: TigerVNC
 - VNC client version: 64-bit v1.10.1
 - Client downloaded from: my Linux distribution

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - VNC server: Xvnc TigerVNC
 - VNC server version: 1.9.0
 - Server downloaded from: my Linux distribution
 - Server was started using: sudo -u user vncserver -localhost no

**Additional context**
It was ok on Ubuntu 19.10, but not working on Ubuntu 20.04

**Comment by CendioOssman** [comment]
Are you sure about that server version? I would assume the server and client has the same version.

This isn't something we've seen before, so we need to pinpoint where the issue might be. To begin with, could you try a different client? (or server)

**Comment by MarkMielke** [comment]
When you say "Go to 'TigerVNC', focus on any text input field"... which applications are you referring to?

I only ask, because I have been seeing a regular hang when pasting from Windows client to Linux remote, pasting into Chrome. However, in my case - it is Chrome that hangs, and Chrome that fails. X, and TigerVNC are fine. I can even close the Chrome tab that is hung, however, a bit later Chrome usually fails. My issue might be entirely different from yours - but I think my main point is to ask you if if it is hanging in all applications, or only a particular set of applications? For example, does paste to a terminal work?

**Comment by wmh** [comment]
Sorry for the late reply. About the server version. I saw it in the log file. It was Xvnc TigerVNC 1.9.0, and it is Xvnc TigerVNC 1.10.0 now. And I cannot reproduce this issue now. I'm not sure if it's related to the server version or not.

```
Xvnc TigerVNC 1.10.0 - built Apr  9 2020 06:49:31
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12008000, The X.Org Foundation
```

About MarkMielke's question. I was pasting text to Chrome, and sorry I cannot reproduce to check if it's the same with other applications.

**Comment by qsimpleq** [comment]
> I was pasting text to Chrome, and sorry I cannot reproduce to check if it's the same with other applications.

Please, update both to 1.10.1.
For me seems that same problem was fixed.

was:
```
client: 1.10.1
server: 1.10.0
problem: copy from client some unicode phrase, to server in "visual studio code", Press 'Ctrl-V' and it looks like hanged
```

Now did update server to 1.10.1. and it seems work normally.

**Comment by MarkMielke** [comment]
Chrome still fails for me, including with 1.10.1. However, I've analyzed this previously and found that it only happens in Chrome, and it is Chrome that hangs and then later fails. I'm 90%+ sure this is a Chrome problem, and I don't have time to look further. So, just sharing my experience here that there is a known issue with paste into Chrome, but I don't think there is evidence that TigerVNC is the cause.

**Comment by wmh** [comment]
I found the steps to reproduce it.

**To Reproduce**
Steps to reproduce the behavior:

1. Copy Text From 'Host'
2. Paste it to any applications in 'TigerVNC', say 'Text Editor'. It works!
3. Press Ctrl-A to select all text from the application.
4. Press Ctrl-V again to paste the text. It hangs here.

Step 3 press Ctrl-A is the key to reproduce this issue.

**Comment by MarkMielke** [comment]
To Reproduce doesn't seem to work for me. :-) Are you only Ctrl-A and Ctrl-V into "Text Editor"? And using 1.10.1 for client and server? What about nightly for client?

**Comment by qsimpleq** [comment]
> I found the steps to reproduce it.
> 
> **To Reproduce**

Too large text size. Yes, this is reproducable for me in vscode if text size > 90Kb.

But, you can change -MaxCutText=1048576 on client and server.
For most cases this will be enough.

**Comment by wmh** [comment]
> To Reproduce doesn't seem to work for me. :-) Are you only Ctrl-A and Ctrl-V into "Text Editor"? And using 1.10.1 for client and server? What about nightly for client?

Yes, only Ctrl-A and Ctrl-V into "Text Editor" and it hangs. Not yet try 1.10.1 for server, since I already keep it up to date from my distribution.

**Comment by CendioOssman** [comment]
Just to clarify, it's VSCode (or Chrome) that hangs? Not the entire VNC server, or the VNC client?

**Comment by MarkMielke** [comment]
When it has happened for me - it wasn't anything more than a URL copy + paste into Chrome location field.

I believe it also happened once since I last posted above with one of the graphical editors, instead of Chrome.

In both cases, it was strangely the app that hung. In the case of Chrome, it was the one tab - but after killing the tab, Chrome might still fail a minute later. No need to restart Xvnc to clear the problem. Once Chrome is launched again it is back to normal, and I believe the same with graphical editors.

That's for me anyways... For the others that posted, can you confirm if you see the same?

**Comment by meilihao** [comment]
I got the same issue when copy something to vscode.

**Comment by CendioOssman** [comment]
I'm afraid this sounds like a bug in chromium in that case since it's those applications that hang and not TigerVNC.

I would recommend filing a bug with them and let them dig further in to what might be wrong. Feel free to cross reference things with this bug.

**Comment by pelszkow** [comment]
For me helps `-SendPrimary=0`
> Ubuntu 20.04
> Package: tigervnc-standalone-server      
> Version: 1.10.1+dfsg-3
