### ISSUE TITLE
Clipboard content gets lost if something is selected on the server side

### ISSUE THREAD

**Issue by L-U-T-i** [TigerVNC/tigervnc#1251]
**Describe the bug**
If some text is copied to the clipboard on the client side (to be pasted into a target on the server side), it seems to be removed from the clipboard (paste button is greyed out / not available anymore) if something is just selected (not copied!) on the server side before the paste attempt.
It is extremely annoying as many times it is virtually impossible to copy some text to server without selecting anything there before or between paste operations (so, I have to copy the same content on the client side again and again, if I have to paste it to more than just one single place). I also prefer to simply overwrite something with a clipboard content (copied on the client side in advance) instead of erasing it first on the server side, go to the client, copy something, return back to server and paste (risking to paste on the wrong place - if cursor would move unintentionally move in between).

**To Reproduce**
1. Copy some text on the client side
2. In VNC client window (server side), open a text editor or terminal window
3. Paste the clipboard content - it should work as expected
4. Select a part of pasted text or anything else (on the server side)
5. Right click to get the menu with a "paste" entry - it is greyed out now, so no paste anymore...

**Expected behavior**
If nothing has been copied in between, the clipboard content should remain available, nomatter if something has been selected in between or not. So, the "paste" right click menu entry should still be available.

**Screenshots**
Request if needed, please.

**Client (please complete the following information):**
 - OS: Fedora 32 / CentOS 7
 - VNC client: TigerVNC
 - VNC client version: 1.10.1 / custom builds of 1.11.0 and 1.11.80 (git commits up to 89f6d5a) - I guess it doesn't matter
 - Client downloaded from: my Linux distribution / custom builds

**Server (please complete the following information):**
 - OS: CentOS 8.3
 - VNC server: TigerVNC
 - VNC server version: 1.10.1 / custom builds of 1.11.0 and 1.11.80 (git commits up to 89f6d5a)
 - Server downloaded from: my Linux distribution / custom builds
 - Server was started using: systemd

**Additional context**
I've made some custom builds with more recent versions of TigerVNC, to test if the issue has been fixed in between (1.11.0 rebuilt using probably well tested CentOS 8.3 Stream SPEC).

The problems with a clipboard started with CentOS upgrade from 8.2 to 8.3 (so before TigerVNC 1.10.1), if I remember well. Before, everything was working without any issues, as expected. I also beleive it is the server side to be blamed, not the client (I haven't do anything on the Fedora 32 / CentOS 7 side, just upgraded CentOS 8.2 to 8.3 when the issue appeared).

**Comment by CendioOssman** [comment]
We did an overhaul of the clipboard in 1.10.0, so something might have changed at that point.

However the way it currently works was somewhat how it "should" work. VNC only has a single clipboard, unlike two that X11 commonly has. So it has to glue those two together, which means if one is lost so is the other.

Your use case is very reasonable though, so it would be nice if we can come up with some clever way to handle this.

**Comment by L-U-T-i** [comment]
I'm not sure I understand this about one (VNC) and two (X11) clipboards. I'd say that as long as something is just selected, but not copied or cut to the clipboard yet, there should be no reason the old clipboard content is lost (even with one single clipboard). Or, does this technique function in any other way?
In any case, thank you very much for your feedback and support.

**Comment by CendioOssman** [comment]
Under X11 just selecting things puts it in to a (different) clipboard. Many users expect this clipboard to also work over VNC and it's not always clear how to prioritise this over the "normal" clipboard.

**Comment by L-U-T-i** [comment]
Thank you for an explanation. What might be the purpose of putting just selected things into a (second) clipboard? Or, is it just a technique implemented for a "drag & drop" - moving a selected text (or files) in GUI (without them being explicitely cut or copied and pasted)?

If yes, I don't see a real need for that to be shared, even if it might be interesting on some occasions - to be able to also simply drag a selected text (or a file) from a VNC client window (remote VNC system) to a destination on a local system (in this case, VNC should obviously support a share of 2 separate / independent clipboards).

In any case, I hope it can be somehow avoided that the use of this "secondary" clipboard on a remote machine is messing with (clearing) the content of a "normal" shared clipboard. And, what is the actual need for, or a benefit of this (a "normal" clipboard being just cleared, not even the content to be replaced by selection / a use of a "secondary" clipboard at the remote machine) at all?

What also confuses me is the fact, that I haven't noticed the content of a shared clipboard being wiped out if something is selected locally in between. So, there shall be a way to behave in the same manner in both directions, or?

**Comment by CendioOssman** [comment]
This should be fixed now in 95ad4d70925c65ac3c90a10df5a4bf00ad22d90d.

**Comment by L-U-T-i** [comment]
It seems this bug is still not completely fixed - from time to time, it still happens that the old (preselected text on server side) is pasted instead of the new text from client (or, another server) which should replace the old selected text.

Or, sometimes the old clipboard content is pasted instead of the most receltly copied one (client to server direction) even if nothing is selected on the server side.

Clipboard copy / paste works fine 99% of time, and can't find a pattern how to reproduce, unfortunately.

Besides, I'm not sure if it is a feature or a bug - when I first select some text, and launch vncviewer after, the clipboard on the server side is empty (so I have to copy the same text on client again, before I can paste it to a server side). But maybe it should just be like that?

**Comment by CendioOssman** [comment]
> Clipboard copy / paste works fine 99% of time, and can't find a pattern how to reproduce, unfortunately.

If you find a way to reproduce it, then please open a new issue. Until then, it's unfortunately difficult for us to do much about it. :/

> Besides, I'm not sure if it is a feature or a bug - when I first select some text, and launch vncviewer after, the clipboard on the server side is empty (so I have to copy the same text on client again, before I can paste it to a server side). But maybe it should just be like that?

It's expected, but not how we want things to behave. I'm unsure if we have an open issue here in GitHub for it.
