### ISSUE TITLE
Random crashes with H.264 decoder

### ISSUE THREAD

**Issue by CendioOssman** [TigerVNC/tigervnc#1514]
**Describe the bug**
Sometimes the viewer crashes with a segmentation fault when using the H.264 encoding.

**To Reproduce**
1. Set up a server that supports H.264.
2. Connect and use the session as normal.

**Expected behavior**
Connection continues working.

**Client (please complete the following information):**
 - OS: Fedora 35
 - VNC client: TigerVNC
 - VNC client version: 07d4e29042409a0c2d4912d25af8fab71fa71f33
 - Client downloaded from: Own build

**Server (please complete the following information):**
 - OS: Debian 11
 - VNC server: Custom prototype server
 - VNC server version: N/A
 - Server downloaded from: N/A
 - Server was started using: N/A

**Additional context**
Crash info from gdb:

```
Thread 4 "vncviewer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe2ffd640 (LWP 2117530)]
0x00007ffff7ab7f23 in ff_yuv_420_rgb32_ssse3 () from /lib64/libswscale.so.5
─── Assembly ───────────────────────────────────────────────────────────────────────────────────────────
 0x00007ffff7ab7f23  ? movdqu %xmm5,0x20(%rsi)
 0x00007ffff7ab7f28  ? movdqu %xmm3,0x30(%rsi)
 0x00007ffff7ab7f2d  ? movdqu 0x10(%r9,%rdi,2),%xmm6
 0x00007ffff7ab7f34  ? movq   0x8(%rcx,%rdi,1),%xmm1
 0x00007ffff7ab7f3a  ? movq   0x8(%rdx,%rdi,1),%xmm0
 0x00007ffff7ab7f40  ? add    $0x40,%rsi
 0x00007ffff7ab7f44  ? add    $0x8,%rdi
 0x00007ffff7ab7f48  ? js     0x7ffff7ab7e33 <ff_yuv_420_rgb32_ssse3+67>
 0x00007ffff7ab7f4e  ? ret    
 0x00007ffff7ab7f4f  ? nop
─── Breakpoints ────────────────────────────────────────────────────────────────────────────────────────
─── Expressions ────────────────────────────────────────────────────────────────────────────────────────
─── History ────────────────────────────────────────────────────────────────────────────────────────────
─── Memory ─────────────────────────────────────────────────────────────────────────────────────────────
─── Registers ──────────────────────────────────────────────────────────────────────────────────────────
         rax 0x00007fffe2ffc220         rbx 0x00007fffd81ddab0            rcx 0x00007fffd83cba40
         rdx 0x00007fffd839b7c0         rsi 0x00007fffcc0fdfe0            rdi 0xffffffffffffff98
         rbp 0x00007fffe2ffc240         rsp 0x00007fffe2ffc108             r8 0x00007fffd81ddab0
          r9 0x00007fffd8307940         r10 0x0000000000000000            r11 0x0000000000001000
         r12 0x0000000000000300         r13 0x00007fffe2ffc210            r14 0xfffffffffffffe00
         r15 0x00000000000000ee         rip 0x00007ffff7ab7f23         eflags [ SF IF RF ]      
          cs 0x00000033                  ss 0x0000002b                     ds 0x00000000        
          es 0x00000000                  fs 0x00000000                     gs 0x00000000        
─── Source ─────────────────────────────────────────────────────────────────────────────────────────────
─── Stack ──────────────────────────────────────────────────────────────────────────────────────────────
[0] from 0x00007ffff7ab7f23 in ff_yuv_420_rgb32_ssse3
[1] from 0x00007ffff7aaf154 in yuv420_rgb32_ssse3.lto_priv
[2] from 0x00007ffff7a8e05b in sws_scale
[3] from 0x000000000044f588 in rfb::H264LibavDecoderContext::decode(unsigned char const*, unsigned int, unsigned int, rfb::ModifiablePixelBuffer*)+504 at /home/ossman/devel/tigervnc/common/rfb/H264LibavDecoderContext.cxx:225
[4] from 0x000000000044ecce in rfb::H264Decoder::decodeRect(rfb::Rect const&, void const*, unsigned long, rfb::ServerParams const&, rfb::ModifiablePixelBuffer*)+590 at /home/ossman/devel/tigervnc/common/rfb/H264Decoder.cxx:137
[5] from 0x000000000043e200 in rfb::DecodeManager::DecodeThread::worker()+176 at /home/ossman/devel/tigervnc/common/rfb/DecodeManager.cxx:324
[6] from 0x000000000045747a in os::Thread::startRoutine(void*)+10 at /home/ossman/devel/tigervnc/common/os/Thread.cxx:160
[7] from 0x00007ffff589fdb2 in start_thread+722 at pthread_create.c:443
[8] from 0x00007ffff583f9e0 in clone3 at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
─── Threads ────────────────────────────────────────────────────────────────────────────────────────────
[5] id 2117531 name vncviewer from 0x00007ffff589c94a in __futex_abstimed_wait_common64+153 at futex-internal.c:57
[4] id 2117530 name vncviewer from 0x00007ffff7ab7f23 in ff_yuv_420_rgb32_ssse3
[3] id 2117529 name vncviewer from 0x00007ffff589c94a in __futex_abstimed_wait_common64+153 at futex-internal.c:57
[2] id 2117528 name vncviewer from 0x00007ffff589c94a in __futex_abstimed_wait_common64+153 at futex-internal.c:57
[1] id 2117515 name vncviewer from 0x00007ffff589c94a in __futex_abstimed_wait_common64+153 at futex-internal.c:57
─── Variables ──────────────────────────────────────────────────────────────────────────────────────────
────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by CendioOssman** [comment]
@xornet-sl, I'm not familiar with this code, so I'd appreciate if you have some ideas on why this might crash. Likely some buffer size issue.

**Comment by xornet-sl** [comment]
Hi. I need more information about reproduction this issue. We tested h.264 on long-running sessions and nothing happened. But we used our server implementation on raspberry-pi. Maybe there is something unexpected in payload? How long you are waiting before client crashes? Could you please send me a server?

**Comment by CendioOssman** [comment]
After digging, it seems like the H.264 rect is 1×1, which is a bit odd. So, something is a bit funky with the server.

Still, the client shouldn't crash. @xornet-sl, do you think you could simulate this and see if you can come up with a fix?

I'm afraid I'm unable to share the server at this time, so I understand if it's limited how much you can assist.

**Comment by xornet-sl** [comment]
@CendioOssman I understand if you are unable to share the server. But maybe you will be able to launch it for me and give me some network access to test and debug this behavior?
Or could you tcpdump some packets just before a crash?

**Comment by xornet-sl** [comment]
I totally agree that client must tolerate any funky things from server and terminate session normally or blank the screen, but never crash

**Comment by CendioOssman** [comment]
It's currently on an internal server, so I'm afraid not right now.

I can see if I can grab something. But decoding VNC traffic manually is usually a pain since it doesn't have any synchronisation markers. :/

And to add, the received frame is 1024×768, so there is definitely a mismatch in what the server is sending.

**Comment by CendioOssman** [comment]
What I can easily do is give you interesting values from gdb. If there is something that can easily help you.

**Comment by CendioOssman** [comment]
And now I got a different crash. An assert in libswscale instead:

```
Assertion dstY >= ret failed at libswscale/swscale.c:975

Thread 5 "vncviewer" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe2ffd640 (LWP 2173495)]
0x00007ffff58a1afc in __pthread_kill_implementation () from /lib64/libc.so.6
─── Assembly ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0x00007ffff58a1afc  ? mov    %eax,%ebp
 0x00007ffff58a1afe  ? neg    %ebp
 0x00007ffff58a1b00  ? cmp    $0xfffff000,%eax
 0x00007ffff58a1b05  ? mov    $0x0,%eax
 0x00007ffff58a1b0a  ? cmova  %ebp,%eax
 0x00007ffff58a1b0d  ? jmp    0x7ffff58a1a82 <__pthread_kill_implementation+162>
 0x00007ffff58a1b12  ? nopw   0x0(%rax,%rax,1)
 0x00007ffff58a1b18  ? mov    %r13,%rdi
 0x00007ffff58a1b1b  ? call   0x7ffff589cb50 <__lll_lock_wake_private>
 0x00007ffff58a1b20  ? jmp    0x7ffff58a1a69 <__pthread_kill_implementation+137>
─── Breakpoints ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Expressions ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── History ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Memory ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Registers ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   rax 0x0000000000000000       rbx 0x00007fffe2ffd640    rcx 0x00007ffff58a1afc    rdx 0x0000000000000006    rsi 0x0000000000212a37    rdi 0x0000000000212a24   rbp 0x0000000000212a37   rsp 0x00007fffe2ffbf70
    r8 0x00007fffe2ffc040        r9 0x00007ffff59b04e0    r10 0x0000000000000008    r11 0x0000000000000246    r12 0x0000000000000006    r13 0x00007fffe2ffc240   r14 0x0000000000000300   r15 0x00007fffcfd36320
   rip 0x00007ffff58a1afc    eflags [ PF ZF IF ]           cs 0x00000033             ss 0x0000002b             ds 0x00000000             es 0x00000000            fs 0x00000000            gs 0x00000000        
─── Source ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Stack ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[0] from 0x00007ffff58a1afc in __pthread_kill_implementation
[1] from 0x00007ffff58552a6 in raise
[2] from 0x00007ffff58287f3 in abort
[3] from 0x00007ffff7a8e71a in sws_scale
[4] from 0x000000000044f588 in rfb::H264LibavDecoderContext::decode(unsigned char const*, unsigned int, unsigned int, rfb::ModifiablePixelBuffer*)+504 at /home/ossman/devel/tigervnc/common/rfb/H264LibavDecoderContext.cxx:225
[5] from 0x000000000044ecce in rfb::H264Decoder::decodeRect(rfb::Rect const&, void const*, unsigned long, rfb::ServerParams const&, rfb::ModifiablePixelBuffer*)+590 at /home/ossman/devel/tigervnc/common/rfb/H264Decoder.cxx:137
[6] from 0x000000000043e200 in rfb::DecodeManager::DecodeThread::worker()+176 at /home/ossman/devel/tigervnc/common/rfb/DecodeManager.cxx:324
[7] from 0x000000000045747a in os::Thread::startRoutine(void*)+10 at /home/ossman/devel/tigervnc/common/os/Thread.cxx:160
[8] from 0x00007ffff589fdb2 in start_thread
[9] from 0x00007ffff583f9e0 in clone3
─── Threads ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[5] id 2173495 name vncviewer from 0x00007ffff58a1afc in __pthread_kill_implementation
[4] id 2173494 name vncviewer from 0x00007ffff589c94a in __futex_abstimed_wait_common
[3] id 2173493 name vncviewer from 0x00007ffff589c94a in __futex_abstimed_wait_common
[2] id 2173492 name vncviewer from 0x00007ffff589c94a in __futex_abstimed_wait_common
[1] id 2173476 name vncviewer from 0x00007ffff589c94a in __futex_abstimed_wait_common
─── Variables ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by xornet-sl** [comment]
> What I can easily do is give you interesting values from gdb. If there is something that can easily help you.

It would be at least just something. Give me anything you can. It's very, veerrryy limited information, still

**Comment by xornet-sl** [comment]
Um.. Could you run it under debugger and tell me something about local variables prior the `sws_cale` call?

**Comment by CendioOssman** [comment]
So this is for the assert case, since that is what is currently happening:

```
>>> up 4
#4  0x000000000044f588 in rfb::H264LibavDecoderContext::decode (this=0x7fffcc000ba0, h264_in_buffer=<optimized out>, len=<optimized out>, flags=<optimized out>, pb=0x515410) at /home/ossman/devel/tigervnc/common/rfb/H264LibavDecoderContext.cxx:225
225	  sws_scale(sws, frame->data, frame->linesize, 0, frame->height, &swsBuffer, &dst_linesize);
>>> info locals
lock = {
  m = 0x7fffcc000ba8
}
h264_work_buffer = <optimized out>
packet = 0x0
ret = <optimized out>
frames_received = <optimized out>
stride = 1024
dst_linesize = 4096
>>> print *frame
$1 = {
  data = {[0] = 0x7fffcc154b80 "", [1] = 0x7fffcc215400 "", [2] = 0x7fffcc245680 "", [3] = 0x0, [4] = 0x0, [5] = 0x0, [6] = 0x0, [7] = 0x0},
  linesize = {[0] = 1024, [1] = 512, [2] = 512, [3] = 0, [4] = 0, [5] = 0, [6] = 0, [7] = 0},
  extended_data = 0x7fffcc00f040,
  width = 1024,
  height = 768,
  nb_samples = 0,
  format = 0,
  key_frame = 1,
  pict_type = AV_PICTURE_TYPE_I,
  sample_aspect_ratio = {
    num = 0,
    den = 1
  },
  pts = -9223372036854775808,
  pkt_pts = -9223372036854775808,
  pkt_dts = -9223372036854775808,
  coded_picture_number = 0,
  display_picture_number = 0,
  quality = 0,
  opaque = 0x0,
  error = {[0] = 0, [1] = 0, [2] = 0, [3] = 0, [4] = 0, [5] = 0, [6] = 0, [7] = 0},
  repeat_pict = 0,
  interlaced_frame = 0,
  top_field_first = 0,
  palette_has_changed = 0,
  reordered_opaque = -9223372036854775808,
  sample_rate = 0,
  channel_layout = 0,
  buf = {[0] = 0x7fffcc2e0b80, [1] = 0x7fffcc2e0940, [2] = 0x7fffcc2e0c80, [3] = 0x0, [4] = 0x0, [5] = 0x0, [6] = 0x0, [7] = 0x0},
  extended_buf = 0x0,
  nb_extended_buf = 0,
  side_data = 0x0,
  nb_side_data = 0,
  flags = 0,
  color_range = AVCOL_RANGE_UNSPECIFIED,
  color_primaries = AVCOL_PRI_UNSPECIFIED,
  color_trc = AVCOL_TRC_UNSPECIFIED,
  colorspace = AVCOL_SPC_UNSPECIFIED,
  chroma_location = AVCHROMA_LOC_LEFT,
  best_effort_timestamp = -9223372036854775808,
  pkt_pos = -1,
  pkt_duration = 0,
  metadata = 0x0,
  decode_error_flags = 0,
  channels = 0,
  pkt_size = 68760,
  qscale_table = 0x0,
  qstride = 0,
  qscale_type = 0,
  qp_table_buf = 0x0,
  hw_frames_ctx = 0x0,
  opaque_ref = 0x0,
  crop_top = 0,
  crop_bottom = 0,
  crop_left = 0,
  crop_right = 0,
  private_ref = 0x0
}
>>> print *this
$2 = {
  <rfb::H264DecoderContext> = {
    _vptr.H264DecoderContext = 0x47a340 <vtable for rfb::H264LibavDecoderContext+16>,
    mutex = {
      systemMutex = 0x7fffcc000c10
    },
    rect = {
      tl = {
        x = 0,
        y = 0
      },
      br = {
        x = 1,
        y = 1
      }
    },
    initialized = true
  }, 
  members of rfb::H264LibavDecoderContext:
  avctx = 0x7fffcc001b00,
  parser = 0x7fffcc000c40,
  frame = 0x7fffcc00f040,
  sws = 0x7fffcc045240,
  swsBuffer = 0x7fffcc010320 "\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377\365\364\366\377"...,
  h264WorkBuffer = 0x7fffcc021a40 "\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377\362\365\365\377"...,
  h264WorkBufferLength = 68784
}
>>> print *pb
$3 = {
  <rfb::PixelBuffer> = {
    _vptr.PixelBuffer = 0x459e20 <vtable for PlatformPixelBuffer+16>,
    format = {
      bpp = 32,
      depth = 24,
      trueColour = true,
      bigEndian = false,
      redMax = 255,
      greenMax = 255,
      blueMax = 255,
      redShift = 16,
      greenShift = 8,
      blueShift = 0,
      redBits = 8,
      greenBits = 8,
      blueBits = 8,
      maxBits = 8,
      minBits = 8,
      endianMismatch = false
    },
    width_ = 1024,
    height_ = 768
  }, <No data fields>}
```

**Comment by xornet-sl** [comment]
Ok. With this I'll try to reproduce this behavior. But today I'm flying to the different country for vacation. And I don't know if I can fix it right away. How fast it should be fixed?

**Comment by CendioOssman** [comment]
No rush at all. This is a very early test. I just didn't want the information to get lost.

**Comment by cgm999** [comment]
Hi, 
I may had found what is going on with this issue , @CendioOssman  does the issue still manifest for you on latest commit ?

**Comment by cgm999** [comment]
Hi @xornet-sl  , can you please add some light why in common/rfb/H264Decoder.cxx we have:
  if (flags & resetContext) {                                                                                                                                  
    ctx->reset();                                                                                                                                              
  }
I do not see where flags is set.
The issue is H264 is reset for every packet and that causes some problems..

**Comment by any1** [comment]
I've run `sws_scale` crashes myself.

Valgrind sheds a bit of light on the issue.

```
==264973== Invalid write of size 8
==264973==    at 0x73B3D48: ??? (in /usr/lib/libswscale.so.8.1.100)
==264973==    by 0x1C126A7F: ???
==264973==    by 0x1C166DBF: ???
==264973==  Address 0x1bf5b150 is 0 bytes after a block of size 3,911,952 alloc'd
==264973==    at 0x48445F3: operator new[](unsigned long) (vg_replace_malloc.c:729)
==264973==    by 0x1817ED: rfb::H264LibavDecoderContext::initCodec() (H264LibavDecoderContext.cxx:91)
==264973==    by 0x18147B: rfb::H264DecoderContext::reset() (H264DecoderContext.cxx:63)
==264973==    by 0x17FA79: rfb::H264Decoder::decodeRect(rfb::Rect const&, unsigned char const*, unsigned long, rfb::ServerParams const&, rfb::ModifiablePixelBuffer*) (H264Decoder.cxx:135)
==264973==    by 0x16663D: rfb::DecodeManager::DecodeThread::worker() (DecodeManager.cxx:318)
==264973==    by 0x196864: os::Thread::startRoutine(void*) (Thread.cxx:160)
==264973==    by 0x7B6BDEC: start_thread (pthread_create.c:447)
==264973==    by 0x7BEEEE3: clone (clone.S:100)
```

The problem is that the destination buffer is allocated with a size of `rect.width * rect.height * pixel-size`, but `sws_scale` is called with the `ModifiablePixelBuffer`'s stride and the decoded frame's height. There are two problems with this:
 * `rect.width` might not be the same as the stride of `bp`.
 * The frame's height might be greater than than that of `bp`.

Although it may look to be wrong of the server to send a frame with a height that exceeds the rect's height, it is actually something that may happen due to constraints set be hardware encoders. Some of them can only encode videos with height divisible by a certain factor (usually 16 or 32), so the client needs to be able to cope with this by trimming off the excess.

It would be best to have `sws_scale` write directly into the `ModifiablePixelBuffer`, but that requires a bit more work.

This fixes it for me:

```
diff --git a/common/rfb/H264LibavDecoderContext.cxx b/common/rfb/H264LibavDecoderContext.cxx
index 5bd1dbbf..ec909d46 100644
--- a/common/rfb/H264LibavDecoderContext.cxx
+++ b/common/rfb/H264LibavDecoderContext.cxx
@@ -222,9 +222,15 @@ void H264LibavDecoderContext::decode(const uint8_t* h264_in_buffer,
 
   int stride;
   pb->getBuffer(rect, &stride);
-  int dst_linesize = stride * pb->getPF().bpp/8;  // stride is in pixels, linesize is in bytes (stride x4). We need bytes
 
-  sws_scale(sws, frame->data, frame->linesize, 0, frame->height, &swsBuffer, &dst_linesize);
+  int height = frame->height;
+  if (height > rect.height())
+    height = rect.height();
 
-  pb->imageRect(rect, swsBuffer, stride);
+  int dst_linesize = rect.width() * pb->getPF().bpp / 8;
+
+  sws_scale(sws, frame->data, frame->linesize, 0, height, &swsBuffer,
+            &dst_linesize);
+
+  pb->imageRect(rect, swsBuffer);
 }

```

**Comment by cgm999** [comment]
sws_scale is what I see as the source of the crash ( exactly as any1 explained above, writes more data after that allocated buffer, in my case source is PiKVM and writes extra 32 bytes after end of buffer ) .. even if when I run with valgrind it did not made it crash.

Offtopic, there is also a memleak  in H264LibavDecoderContext::decode() , we also need to 
  sws_freeContext(sws);
after sws_scale(..)

Also sws_getCachedContext returns a new pointer every time(at least for my case PiKVM) , does it even make sense to use it ? instead of sws_getContext

**Comment by cgm999** [comment]
I did look more into this, I do not think I am hitting the same issue as any1 above, since in my case the frame->height or frame->width are the correct values. However sws_scale for some resolutions (I am using ffmpeg to convert a sample h264 into 1024x768 , 1026x768, etc) and we can see where the overflow happens:

`
frame->width=1024 frame->height=768 dec_ctx->coded_width=1024 dec_ctx->coded_height=768

00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
frame->width=1026 frame->height=768 dec_ctx->coded_width=1040 dec_ctx->coded_height=768

00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
frame->width=1028 frame->height=768 dec_ctx->coded_width=1040 dec_ctx->coded_height=768

00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
frame->width=1030 frame->height=768 dec_ctx->coded_width=1040 dec_ctx->coded_height=768

00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
frame->width=1032 frame->height=768 dec_ctx->coded_width=1040 dec_ctx->coded_height=768

00 84 00 FF 00 84 00 FF  00 84 00 FF 00 84 00 FF  |  ................ 
00 84 00 FF 00 84 00 FF  00 84 00 FF 00 84 00 FF  |  ................ 
frame->width=1034 frame->height=768 dec_ctx->coded_width=1040 dec_ctx->coded_height=768

00 84 00 FF 00 84 00 FF  00 84 00 FF 00 84 00 FF  |  ................ 
00 84 00 FF 00 84 00 FF  00 00 00 00 00 00 00 00  |  ................ 
frame->width=1036 frame->height=768 dec_ctx->coded_width=1040 dec_ctx->coded_height=768

00 83 00 FF 00 83 00 FF  00 83 00 FF 00 83 00 FF  |  ................ 
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
frame->width=1038 frame->height=768 dec_ctx->coded_width=1040 dec_ctx->coded_height=768

00 84 00 FF 00 84 00 FF  00 00 00 00 00 00 00 00  |  ................ 
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
frame->width=1040 frame->height=768 dec_ctx->coded_width=1040 dec_ctx->coded_height=768

00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
frame->width=1042 frame->height=768 dec_ctx->coded_width=1056 dec_ctx->coded_height=768

00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................ 
`

**Comment by cgm999** [comment]
After more research, the issue that I think that my issue is related to alligment(  height /width not multiple of 16)   ,similar how any1 explained, however for me I do see the expected value in frame->width or frame->height. 

I propose to align the swsBuffer to cpu align and add extra room (maybe 128 bytes), where sws_scale will write extra bogus data (which we will ignore). An example of how is done in other places that uses sws_scale:

```
         AVFrame* pic_out = av_frame_alloc();                                                                                                                  
         pic_out->format = AV_PIX_FMT_RGB32;                                                                                                                   
         pic_out->width  = frame->width;                                                                                                                       
         pic_out->height = frame->height;                                                                                                                      
         av_frame_get_buffer( pic_out,  av_cpu_max_align() ); // last arg is allign, 0 will be replaced with 32                                                                                    

         sws_scale(sws, (const uint8_t * const*)frame->data, frame->linesize, 0, frame->height, pic_out->data, pic_out->linesize);                             


```

**Comment by any1** [comment]
Yeah, the buffer needs to be aligned for SIMD.

**Comment by cgm999** [comment]
Do we still need this open?

**Comment by CendioOssman** [comment]
No we do not. :)
