### ISSUE TITLE
Crash when using particular program

### ISSUE THREAD

**Issue by snmishra** [TigerVNC/tigervnc#237]
Xvnc crashes quite frequently when using TigerVNC 1.5.0 on Centos 6.6 x86_64 with a particular EDA tool (Mentor Graphics Calibre). It doesn't happen right away, but as the GUI is updating the progress.

The following is the backtrace in the log file:

```
(EE) 0: /usr/bin/Xvnc (xorg_backtrace+0x44) [0x6dc8e4]
(EE) 1: /usr/bin/Xvnc (0x400000+0x2e0869) [0x6e0869]
(EE) 2: /lib64/libpthread.so.0 (0x3f4fa00000+0xf790) [0x3f4fa0f790]
(EE) 3: /usr/bin/Xvnc (rfb::Region::get_rects(std::vector<rfb::Rect, std::alloca
tor<rfb::Rect> >*, bool, bool, int) const+0x176) [0x566416]
(EE) 4: /usr/bin/Xvnc (rfb::ComparingUpdateTracker::compare()+0x15d) [0x56acfd]
(EE) 5: /usr/bin/Xvnc (rfb::VNCServerST::checkUpdate()+0x2b7) [0x5687a7]
(EE) 6: /usr/bin/Xvnc (rfb::VNCSConnectionST::writeFramebufferUpdate()+0x180) [0
x576c60]
(EE) 7: /usr/bin/Xvnc (rfb::VNCSConnectionST::writeFramebufferUpdateOrClose()+0x
d) [0x57769d]
(EE) 8: /usr/bin/Xvnc (rfb::VNCServerST::tryUpdate()+0x5f) [0x568d4f]
(EE) 9: /usr/bin/Xvnc (rfb::VNCServerST::handleTimeout(rfb::Timer*)+0x25) [0x568
dc5]
(EE) 10: /usr/bin/Xvnc (rfb::Timer::checkTimeouts()+0x6e) [0x574e8e]
(EE) 11: /usr/bin/Xvnc (rfb::VNCServerST::checkTimeouts()+0x1e) [0x5672ae]
(EE) 12: /usr/bin/Xvnc (XserverDesktop::readWakeupHandler(fd_set*, int)+0x351) [
0x558471]
(EE) 13: /usr/bin/Xvnc (vncCallReadWakeupHandlers+0x34) [0x54ea14]
(EE) 14: /usr/bin/Xvnc (0x400000+0x15566c) [0x55566c]
(EE) 15: /usr/bin/Xvnc (WakeupHandler+0x5b) [0x68cf4b]
(EE) 16: /usr/bin/Xvnc (WaitForSomething+0x217) [0x6da457]
(EE) 17: /usr/bin/Xvnc (Dispatch+0xb2) [0x688a92]
(EE) 18: /usr/bin/Xvnc (dix_main+0x41a) [0x68c89a]
(EE) 19: /lib64/libc.so.6 (__libc_start_main+0xfd) [0x3f4f21ed5d]
(EE) 20: /usr/bin/Xvnc (0x400000+0x6b4e9) [0x46b4e9]
(EE)
(EE) Floating point exception at address 0x566416
(EE)
Fatal server error:
(EE) Caught signal 8 (Floating point exception). Server aborting
(EE)
```

**Comment by bphinz** [comment]
This was fixed back in September (see #184). Can you please try the latest
nightly build and confirm?

Thanks,
-brian

**Comment by snmishra** [comment]
Brian,

Sorry for not checking first. The nightly fixes it.

Satya

**Comment by snmishra** [comment]
As it turns out, it didn't fix it completely. I just experienced a crash with nightly and the backtrace looks very similar.

**Comment by CendioOssman** [comment]
Another fix was done in db821a236ff90db5251f99331e37f4fac85654a6. Could you test a nightly build again?

**Comment by snmishra** [comment]
I ran Calibre twice and didn't see this crash with the latest nightly. Thanks for the fix.
