### ISSUE TITLE
"Stuck" keys in TigerVNC Server when pressing Shift + {key}, then releasing Shift and {key} in the same order

### ISSUE THREAD

**Issue by dcommander** [TigerVNC/tigervnc#345]
A TurboVNC user pointed out this issue that also seems to affect the TigerVNC Server (no surprise, given that I borrowed TigerVNC's XKEYBOARD handler logic):

https://sourceforge.net/p/turbovnc/discussion/general/thread/fc5ce4ab/?limit=25

I was able to fix it by patching the XKEYBOARD handler as follows:

```
diff --git a/unix/Xvnc/programs/Xserver/hw/vnc/kbdptr.c b/unix/Xvnc/programs/Xserver/hw/vnc/kbdptr.c
index 218f733..5b42c57 100644
--- a/unix/Xvnc/programs/Xserver/hw/vnc/kbdptr.c
+++ b/unix/Xvnc/programs/Xserver/hw/vnc/kbdptr.c
@@ -213,6 +213,14 @@ void KeyEvent(CARD32 keysym, Bool down)
     if (xkbDebug)
       rfbLog("Unexpected release of keysym 0x%x\n", keysym);
 
+    state = GetKeyboardState();
+    keycode = KeysymToKeycode(keysym, state, &new_state);
+    if (keycode == 0) {
+      if (xkbDebug)
+        rfbLog("Could not get keycode for keysym 0x%x\n", keysym);
+      return;
+    }
+    PressKey(kbdDevice, keycode, FALSE, "keycode");
     return;
   }
```

I think the equivalent patch for TigerVNC would be:

```
diff --git a/unix/xserver/hw/vnc/Input.c b/unix/xserver/hw/vnc/Input.c
index 55befa7..970ac24 100644
--- a/unix/xserver/hw/vnc/Input.c
+++ b/unix/xserver/hw/vnc/Input.c
@@ -394,6 +394,14 @@ void vncKeyboardEvent(KeySym keysym, int down)
                 * key presses.
                 */
                LOG_DEBUG("Unexpected release of keysym 0x%x", keysym);
+
+               state = vncGetKeyboardState();
+               keycode = vncKeysymToKeycode(keysym, state, &new_state);
+               if (keycode == 0) {
+                       LOG_DEBUG("Could not get keycode for keysym 0x%x", keysym);
+                       return;
+               }
+               pressKey(vncKeyboardDev, keycode, FALSE, "keycode");
                return;
        }
```

but I wanted to get your opinion on it (in particular @CendioOssman's opinion, since he wrote the handler.)  I'm not sure whether this is specific to U.S. keyboards, but in our testing, what happens is this:

* If you press Shift, then {some key}, then release {some key}, then release Shift, everything works fine.
* If you press Shift, then {some key}, then release Shift, then release {some key}, then the server generates the "unexpected release" message, and the key remains pressed, according to XQueryKeymap() (refer to the `stuck` test application, the source code for which is available at the above link.)  This is because the Shift state changed between the press and release events, so the keysym is different from the one that was pressed.

Perhaps you can think of a more elegant fix.  I don't confess to have any great knowledge of how the XKEYBOARD handler works.

**Comment by CendioOssman** [comment]
This sounds like a client bug. Does it happen with the TigerVNC client? Perhaps the TurboVNC client lacks code to compensate for the fact that you can get a different keysym on release?

**Comment by dcommander** [comment]
Does the RFB spec have anything to say about the matter?  If it is specified that the client is supposed to send a matching release event for every press event, then I agree with you that this is something our viewer needs to handle.  And you are correct that the TigerVNC Viewer produces correct behavior.  However, the latest TightVNC Viewer does not, and there are probably other viewers that don't do the "right thing" as well, so the server should probably accommodate that regardless.

As the developer of the XKEYBOARD handler, do you see any potential downside for including the code above?

**Comment by dcommander** [comment]
I will elaborate a bit on this.  Most O/S's (possibly even all) send a different symbol for the key release event if Shift is released prior to the modified key.  RFB was originally designed to pass through those events from client to server, and at least in terms of keyboard handling, it was designed around the behavior of X11 (which is why it uses X11 keysyms.)  So it makes sense to me that any RFB server should be able to handle situations in which a different symbol is sent for the key release, since that's in fact what X11 does.

**Comment by CendioOssman** [comment]
> Does the RFB spec have anything to say about the matter? If it is specified that the client is supposed to send a matching release event for every press event, then I agree with you that this is something our viewer needs to handle. And you are correct that the TigerVNC Viewer produces correct behavior. However, the latest TightVNC Viewer does not, and there are probably other viewers that don't do the "right thing" as well, so the server should probably accommodate that regardless.
> 

The spec has overlooked this issue (like so many other things). But having the client handle this is the only way it can work. The server has no idea which keysyms on the client map to the same physical key.

> As the developer of the XKEYBOARD handler, do you see any potential downside for including the code above?

You may send a key release event for an entirely unrelated key. That code will only work for keys where the client's layout is in sync with the server's.

**Comment by dcommander** [comment]
I see your point. Thanks for the clarification.

**Comment by javabrett** [comment]
I stumbled upon this issue, since for me it seems like every Linux VNC viewer or server combination I've tried exhibited this exact same issue.  For me it is usually what I call the double-quote-many-single-quotes issue e.g `"''''''''''''''''''''` - because of the way I type a (double) quotation mark (`U+0022`), my keypress events look like (my interpretation):

- `Shift_R (0x0000ffe2) DOWN`
- `" (0x00000022) DOWN`
- `Shift_R (0x0000ffe2) UP`
- `" (0x00000022) UP`

That is, I (seem to) release the shift key momentarily before releasing the shifted key, perhaps running the risk of typing the unshifted character for that key, especially if keyboard repeat is enabled.

Wireshark has an excellent VNC protocol dissector, so I ran a capture.  I was using Remmina+VNC plugin and TigherVNC server.  Here's what I saw sent by the client for the above sequence:

```
Virtual Network Computing
    Client Message Type: Key Event (4)
        Key down: Yes
        Padding
        Key: Shift_R (0x0000ffe2)

Virtual Network Computing
    Client Message Type: Key Event (4)
        Key down: Yes
        Padding
        Key: " (0x00000022)

Virtual Network Computing
    Client Message Type: Key Event (4)
        Key down: No
        Padding
        Key: Shift_R (0x0000ffe2)

Virtual Network Computing
    Client Message Type: Key Event (4)
        Key down: No
        Padding
        Key: ' (0x00000027)
```

As you can see, the order matches my above assertion - the key-up event is for `Key: ' (0x00000027)`, an `APOSTROPHE` not the `QUOTATION MARK` that shows for the key-down.  There is no matching key-up for the quotation mark.  Oddly this is interpreted as ongoing press of the unshifted key, resulting in `"''''''''''''''''`.

I will try an re-test with pure Tiger server and client and see what I find.  But I thought I would put my analysis here for any benefit to others, and because this seems to be an informed discussion here.

What is the assertion of correct behaviour here - that VNC clients should always make sure they send a matching key-up event, even if the shift-key is released early?  The server seems to have an odd interpretation of the state - a key-down=no for the apostrophe is resulting in a key-repeat for that key!  I can only assume that the server thinks a key is still down, it was a quotation-mark, but since shift is now released, it repeats it as an apostrophe (unshifted).

**Comment by javabrett** [comment]
I am very happy to say that, TigerVNC Viewer 64-bit v1.8.0 does _not_ exhibit this problem, even when the server is an ancient version of 1.1.0-16.  So this must have been fixed in the client somewhere along the way, which is awesome.

**Comment by lodagro** [comment]
Upgraded to TigerVNC Viewer 64-bit v1.8.0 specifically for this issue. Unfortunately TigerVNC Viewer 64-bit v1.8.0 -for me at least- did not resolve this. For example typing <Shift>+0 and releasing <shift> first, a number of 0 are added automagically.
Server is running on redhat6, client on Windows 10.

**Comment by dcommander** [comment]
@lodagro The original issue turned out to be a problem with the TurboVNC Viewer's keyboard handling implementation, so this specific issue was not a TigerVNC bug.  You may be experiencing an unrelated issue.

**Comment by CendioOssman** [comment]
What he said. 👆 

Please open a new issue with more details on your setup.

**Comment by kmatveyonok** [comment]
> resulting in "''''''''''''''''.
I have the same issue. But setup is
1. KRDC client
2. XVnc server/ Slackware Linux/ KDE
3. VirtualBox 5.2.2 running Linux guests (Slackware, ubuntu)
And the problem for some reason exists inside VirtualBox guest.

**Comment by lodagro** [comment]
hmm, the issue i have is as exactly described in the title of this issue
Pressing *shift* + *key*, releasing *shift* before releasing *key* and characters come up automatically until another key is pressed.
For example *shift* + *0* and releasing *shift* before *0*, will start typing zeros until another key is pressed.

Both server and client are tigervnc.

If you want i can open a new issue. What kind of details do you need (besides version of server, client, operating system details)?

**Comment by CendioOssman** [comment]
That would be a good start. Also include how you set up and started the server.
