### ISSUE TITLE
vncviewer traps input on single full screen even when mouse leaves that screen in multiple monitor configuration

### ISSUE THREAD

**Issue by jagmarz** [TigerVNC/tigervnc#447]
TigerVNC Viewer 64-bit v1.8.80
Built on: 2017-04-25 00:05
Debian 9.0, amd64
Running windowmaker on both local and VNC desktop

I like having my VNC fill one of my two monitors (full-screen mode, but not all monitors), but when I do this, the mouse can leave that screen, but the focus remains on the VNC session. This is "fixed" by turning off sending system keys, but then I can't interact properly with the full-screen VNC session. Ouch.

I don't have much X programming experience, but it seems that vncviewer ought to notice that the mouse has left the screen and relinquish focus when it does.

**Comment by teledyn** [comment]
I have the same issue here, using an external monitor on an HP laptop running Ubuntu 17.05 with gnome-shell (which is already quirky) -- as with the original report, I use the monitor for a full-screen tigervncviewer display and my laptop for localhost, and I am running tiger vncviewer (1.7.0+dfsg-7ubuntu1) over an ssh tunnel (if that matters)

I find a more elegant work-around is to open the F8 menu and then click "Dismiss", this nearly always frees focus back to my laptop monitor.

**Comment by CendioOssman** [comment]
Fixed in 7e546febadb6e6cc66138c2316c8c19ca8aab2b1.

**Comment by tempest766** [comment]
recently started switching VMs from virtualBox to QEMU and noticed this problem.

not fixed in 1.9.0-2... still exhibits the bad behaviour.  two distinct X displays running on a server; :0.0 and :0.1.  fullscreen vncviewer showing win7 client on :0.1.  mouse can leave :0.1 and go to :0.0 but input focus is still locked on fullscreen vncviewer
