### ISSUE TITLE
tigervnc-server error in centos 7 mate desktop enviroment!

### ISSUE THREAD

**Issue by iamybj** [TigerVNC/tigervnc#557]
I use centos 7 on my office computer.   Office VPN only open the microsoft remote desktop port.
So I want install xrdp in centos so that I can connect this computer remotely in Windows.
I never in stall gnome in centos 7, just install the minimal system, and then install "x window system" and "mate desktop" group (epel repository has been installed).
But for several days I cannot connect to this centos computer.
I think tigervnc never beed tested under pure mate-deskop enviroment.
There is not only gnome and kde desktop in the world. mate, cinnamon, xfce, lxde should be tested too.
Any body some ideas ?

**Comment by CendioOssman** [comment]
All of those desktop environments work just fine with TigerVNC. You need to describe a bit more how you've set up your server and what error you are seeing.

**Comment by iamybj** [comment]
where is the official instructions of setting tigervnc-server ?

**Comment by CendioOssman** [comment]
http://tigervnc.org/doc/Xvnc.html
http://tigervnc.org/doc/vncserver.html
http://tigervnc.org/doc/x0vncserver.html
https://github.com/TigerVNC/tigervnc/blob/master/contrib/packages/rpm/el7/SOURCES/vncserver.service

**Comment by iamybj** [comment]
Dec 14 20:44:07 pc-aaa systemd: Failed at step USER spawning /usr/bin/vncserver: No such process
Dec 14 20:44:07 pc-aaa systemd: Failed at step USER spawning /usr/bin/vncserver: No such process
Dec 14 20:44:07 pc-aaa systemd: vncserver@:0.service: control process exited, code=exited status=217
Dec 14 20:44:07 pc-aaa systemd: Unit vncserver@:0.service entered failed state.
Dec 14 20:44:07 pc-aaa systemd: vncserver@:0.service failed.

**Comment by CendioOssman** [comment]
That's odd. Does `/usr/bin/vncserver` exist?

**Comment by iamybj** [comment]
● vncserver@:0.service - Remote desktop service (VNC)
   Loaded: loaded (/etc/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-12-14 20:50:25 CST; 13s ago
  Process: 2740 ExecStart=/usr/bin/vncserver %i (code=exited, status=217/USER)
  Process: 2738 ExecStartPre=/usr/bin/vncserver -kill %i (code=exited, status=217/USER)

Dec 14 20:50:25 pc-bingjuny systemd[1]: Starting Remote desktop service (VNC)...
Dec 14 20:50:25 pc-bingjuny systemd[2738]: Failed at step USER spawning /usr/bin/vncserver: No such process
Dec 14 20:50:25 pc-bingjuny systemd[2740]: Failed at step USER spawning /usr/bin/vncserver: No such process
Dec 14 20:50:25 pc-bingjuny systemd[1]: vncserver@:0.service: control process exited, code=exited status=217
Dec 14 20:50:25 pc-bingjuny systemd[1]: Failed to start Remote desktop service (VNC).
Dec 14 20:50:25 pc-bingjuny systemd[1]: Unit vncserver@:0.service entered failed state.
Dec 14 20:50:25 pc-bingjuny systemd[1]: vncserver@:0.service failed.

**Comment by CendioOssman** [comment]
Ehm... that didn't really answer the question?

**Comment by iamybj** [comment]
another 2 ploblem,

1, I want to use display 0, share the same screen as my console desktop in vnc, but when 'systemctl restart vncserver@:0' timeout:
Job for vncserver@:0.service failed because a timeout was exceeded. See "systemctl status vncserver@:0.service" and "journalctl -xe" for details.

2, when use display 1, just a backgroud

**Comment by CendioOssman** [comment]
vncserver is only a background server. If you wish to see your local screen then you need to use libvnc.so (which unfortunately lacks documentation), x0vncserver or some other VNC project.

**Comment by iamybj** [comment]
Tigervnc document is only just man files.
Why not write a hand-by-hand manual for some newbie? 
May be with xrdp is better.

**Comment by CendioOssman** [comment]
Our resources are limited and noone has written any guide here. However there are lots of guides available elsewhere.

**Comment by iamybj** [comment]
Wow, after add mate desktop code in /etc/X11/xinit/Xclients
and add DESKTOP=MATE in /etc/sysconfig/desktop
it works.
but how to make it share the same display 0  with console desktop?

**Comment by CendioOssman** [comment]
The issue here is resolved and #560 has been opened for local console access.

**Comment by sjsdfg** [comment]
i faced the same problem too.
i used command `find / -name 'vncserver'`, it exists in my /usr/bin dircetory.
It still failed.
```
?.vncserver@:1.service - Remote desktop service (VNC)
   Loaded: loaded (/usr/lib/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-03-05 14:52:46 CST; 1min 46s ago
  Process: 1230 ExecStart=/usr/bin/vncserver %i (code=exited, status=217/USER)
  Process: 1218 ExecStartPre=/usr/bin/vncserver -kill %i (code=exited, status=217/USER)

Mar 05 14:52:46 i-6d7c3830 systemd[1]: Starting Remote desktop service (VNC)...
Mar 05 14:52:46 i-6d7c3830 systemd[1218]: Failed at step USER spawning /usr/bin/vncserver: No such process
Mar 05 14:52:46 i-6d7c3830 systemd[1]: vncserver@:1.service: control process exited, code=exited status=217
Mar 05 14:52:46 i-6d7c3830 systemd[1]: Failed to start Remote desktop service (VNC).
Mar 05 14:52:46 i-6d7c3830 systemd[1]: Unit vncserver@:1.service entered failed state.
Mar 05 14:52:46 i-6d7c3830 systemd[1]: vncserver@:1.service failed.
```

**Comment by MikeMoralesDEV** [comment]
Exactly the same problem here, but I didn't solve adding DESKTOP=MATE in /etc/sysconfig/desktop or something like that.
Some ideas? @sjsdfg  do you solve it ?

**Comment by MikeMoralesDEV** [comment]
I haven't multiple Desktop, @iamybj so I haven't /etc/sysconfig/desktop

Then in /etc/X11/xinit/Xclients, when do the condition, it'll execute 
if [ -n "$PREFERRED" ]; then
    exec "$PREFERRED"
fi

My entire file is:
GSESSION="$(type -p gnome-session)"
STARTKDE="$(type -p startkde)"

# check to see if the user has a preferred desktop
PREFERRED=
if [ -f /etc/sysconfig/desktop ]; then
    . /etc/sysconfig/desktop
    if [ "$DESKTOP" = "GNOME" ]; then
        PREFERRED="$GSESSION"
    elif [ "$DESKTOP" = "KDE" ]; then
        PREFERRED="$STARTKDE"
    fi
fi

if [ -n "$PREFERRED" ]; then
    exec "$PREFERRED"
fi

**Comment by sjsdfg** [comment]
@iamybj 
i sovle it by edit my `vncserver@:1.service`

the part of this is
```
# Clean any existing files in /tmp/.X11-unix environment
ExecStartPre=-/usr/bin/vncserver -kill %i
#ExecStart=/usr/bin/vncserver %i
PIDFile=/root/.vnc/%H%i.pid
#PIDFile=/home/<USER>/.vnc/%H%i.pid
ExecStop=-/usr/bin/vncserver -kill %i
```

it still has some error but it works.

**Comment by iamybj** [comment]
just do as I wrote

**Comment by MikeMoralesDEV** [comment]
@iamybj I answered before.
I had a error always trying to connect it.
The error is this:
abr 09 12:27:13 localhost.localdomain pulseaudio[28218]: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by MikeMoralesDEV** [comment]
Now I can connect with VNC Viewer but no with Remote Desktop of Windows. And it show only Mozilla Firefox. I can't see nothing more.

**Comment by ziaullahhussain** [comment]
[root@vm-rhel ~]# systemctl start vncserver@:1.service
Job for vncserver@:1.service failed because the control process exited with error code. See "systemctl status vncserver@:1.service" and "journalctl -xe" for details.

solution

find / -name 'vncserver'
/usr/bin/vncserver

[root@vm-rhel7 bin]# vncserver
Display all 1585 possibilities? (y or n)n
[root@vm-rhel7 bin]# vncserver

Warning: vm-rhel7.2:1 is taken because of /tmp/.X11-unix/X1
Remove this file if there is no X server vm-rhel7.2:1

Warning: vm-rhel7.2:2 is taken because of /tmp/.X11-unix/X2
Remove this file if there is no X server vm-rhel7.2:2
xauth: (stdin):1:  bad display name "vm-rhel7.2:3" in "add" command

New 'vm-rhel7.2:3 (root)' desktop is vm-rhel7.2:3

Starting applications specified in /root/.vnc/xstartup
Log file is /root/.vnc/vm-rhel7.2:3.log

cd/temp
[root@vm-rhel7 tmp]# rm -rf .X11-unix/X1
[root@vm-rhel7 tmp]# rm -rf .X11-unix/X2


[root@vm-rhel7]# systemctl start vncserver@:1.service
[root@vm-rhel7]# systemctl start vncserver@:2.service

its done.

**Comment by ziaullahhussain** [comment]
> i faced the same problem too.
> i used command `find / -name 'vncserver'`, it exists in my /usr/bin dircetory.
> It still failed.
> 
> ```
> ?.vncserver@:1.service - Remote desktop service (VNC)
>    Loaded: loaded (/usr/lib/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Mon 2018-03-05 14:52:46 CST; 1min 46s ago
>   Process: 1230 ExecStart=/usr/bin/vncserver %i (code=exited, status=217/USER)
>   Process: 1218 ExecStartPre=/usr/bin/vncserver -kill %i (code=exited, status=217/USER)
> 
> Mar 05 14:52:46 i-6d7c3830 systemd[1]: Starting Remote desktop service (VNC)...
> Mar 05 14:52:46 i-6d7c3830 systemd[1218]: Failed at step USER spawning /usr/bin/vncserver: No such process
> Mar 05 14:52:46 i-6d7c3830 systemd[1]: vncserver@:1.service: control process exited, code=exited status=217
> Mar 05 14:52:46 i-6d7c3830 systemd[1]: Failed to start Remote desktop service (VNC).
> Mar 05 14:52:46 i-6d7c3830 systemd[1]: Unit vncserver@:1.service entered failed state.
> Mar 05 14:52:46 i-6d7c3830 systemd[1]: vncserver@:1.service failed.
>

solution

find / -name 'vncserver'
/usr/bin/vncserver

[root@vm-rhel7 bin]# vncserver
Display all 1585 possibilities? (y or n)n
[root@vm-rhel7 bin]# vncserver

Warning: vm-rhel7.2:1 is taken because of /tmp/.X11-unix/X1
Remove this file if there is no X server vm-rhel7.2:1

Warning: vm-rhel7.2:2 is taken because of /tmp/.X11-unix/X2
Remove this file if there is no X server vm-rhel7.2:2
xauth: (stdin):1:  bad display name "vm-rhel7.2:3" in "add" command

New 'vm-rhel7.2:3 (root)' desktop is vm-rhel7.2:3

Starting applications specified in /root/.vnc/xstartup
Log file is /root/.vnc/vm-rhel7.2:3.log

cd/temp
[root@vm-rhel7 tmp]# rm -rf .X11-unix/X1
[root@vm-rhel7 tmp]# rm -rf .X11-unix/X2


[root@vm-rhel7]# systemctl start vncserver@:1.service
[root@vm-rhel7]# systemctl start vncserver@:2.service
