### ISSUE TITLE
On MacOS 10.13.6 left mouse button does not seem to work

### ISSUE THREAD

**Issue by dmitry-irtegov** [TigerVNC/tigervnc#754]
I am connecting to tightvnc server running lxde on Ubuntu 18.04.
With other VNC clients ( tried RealVNC/Mac and tightvnc/Ubuntu) server works fine.
With TigerVNC, I cannot start icon in .dmg file, it says "Not optimized for current version of MacOS" and does not start (may be this related).  When I directly start Contents/MacOS/TigerVNC Viewer, it starts and connects to server.  Cursor moves and right mouse button works, but not left mouse button.

The console window contains messages:
```
Last login: Thu Oct 25 12:49:55 on ttys004
/Volumes/TigerVNC-1.9.0/TigerVNC\ Viewer\ 1.9.0.app/Contents/MacOS/TigerVNC\ Viewer ; exit;
MacBook-Pro-Irina:~ fat$ /Volumes/TigerVNC-1.9.0/TigerVNC\ Viewer\ 1.9.0.app/Contents/MacOS/TigerVNC\ Viewer ; exit;

TigerVNC Viewer 32-bit v1.9.0
Built on: 2018-08-05 14:36
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
```

**Comment by CendioOssman** [comment]
Those complaints are about macOS dropping support for 32-bit binaries. The nightly builds of TigerVNC are 64-bit though, could you try that? You can find a link on our homepage.

**Comment by dmitry-irtegov** [comment]
I forgot to mention, it not just complains about 32-bit, it does not run.
I tried link http://tigervnc.bphinz.com/nightly/ on homepage and it gives me 404.

**Comment by CendioOssman** [comment]
@bphinz ?

**Comment by dmitry-irtegov** [comment]
This is what link on home page says

**Comment by CendioOssman** [comment]
Sorry, it was a ping to Brian who manages that page. That's his username here. :)

**Comment by bphinz** [comment]
OK, I'll take a look tonight.

**Comment by bphinz** [comment]
The nightly builds page is fixed now

**Comment by dmitry-irtegov** [comment]
Yes, link to nightly builds works now.  But in 25.10 night build problem persists.  Icon in .dmg file does not start anything.

**Comment by CendioOssman** [comment]
I'm afraid I cannot reproduce any of your issues here. Are you running macOS 10.14 or something older?

**Comment by dmitry-irtegov** [comment]
10.13.6, it is mentioned in subject line.

**Comment by CendioOssman** [comment]
Ah, sorry. Missed that. That is the same version I have here, so that just makes things more mysterious.

I have no idea how to debug the bundle launch problem unfortunately. :/

Do you see the mouse button issue with the nightly build as well? That might be easier to dig in to.

**Comment by CendioOssman** [comment]
No response, closing.
