### ISSUE TITLE
Segfault when trying to run with systemd unit file

### ISSUE THREAD

**Issue by GotekSC** [TigerVNC/tigervnc#832]
**Client (please complete the following information):**
 - OS: manjaro
 - VNC client: TigerVNC
 - VNC client version: e.g. 1.9.0
 - Client downloaded from: manjaro-repo

**Server (please complete the following information):**
 - OS: arch (as qemu vm on proxmox host)
 - VNC server: TigerVNC
 - VNC server version: e.g. 1.9.0
 - Server downloaded from: arch-repo
 - Server was started using: systemd unit file

When trying to run the vncserver with a systemd unit file I get following log output:
```
Xvnc TigerVNC 1.9.0 - built Jul 20 2018 11:32:25
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12000000, The X.Org Foundation


Tue May  7 19:07:57 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5977
 vncext:      Listening for HTTP connections on all interface(s), port 5877
 vncext:      created VNC server for screen 0
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
Errors from xkbcomp are not fatal to the X server
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xvnc (OsLookupColor+0x13a) [0x55958bb1351a]
(EE) 1: /usr/lib/libpthread.so.0 (funlockfile+0x50) [0x7f75b9df251f]
(EE) 2: /usr/bin/Xvnc (_ZN14XserverDesktopD2Ev+0xdb) [0x55958ba6f0db]
(EE) 3: /usr/bin/Xvnc (_ZN14XserverDesktopD0Ev+0xa) [0x55958ba6f24a]
(EE) 4: /usr/bin/Xvnc (vncExtensionClose+0x28) [0x55958ba636b8]
(EE) 5: /usr/bin/Xvnc (CloseDownExtensions+0x31) [0x55958bad3071]
(EE) 6: /usr/bin/Xvnc (dix_main+0x3d2) [0x55958bac33c2]
(EE) 7: /usr/lib/libc.so.6 (__libc_start_main+0xf3) [0x7f75b94cbce3]
(EE) 8: /usr/bin/Xvnc (_start+0x2a) [0x55958b99106a]
(EE) 
(EE) Segmentation fault at address 0x8
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
/usr/bin/startxfce4: X server already running on display :77
xrdb: Connection refused
xrdb: Can't open display ':77'
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
```
With this `xstartup`
```
#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
dbus-launch /usr/bin/startxfce4 &
```
and this unit-file
```
[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=simple
User=gotek
PAMName=login
PIDFile=/home/%u/.vnc/%H%i.pid
ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill :%i > /dev/null 2>&1 || :'
ExecStart=/usr/bin/vncserver :%i -geometry 1440x900 -alwaysshared -fg
ExecStop=/usr/bin/vncserver -kill :%i

[Install]
WantedBy=multi-user.target
```
I followed the instructions on https://wiki.archlinux.org/index.php/TigerVNC And what's funny to me is, that with the same exact procedure I got it to run flawlessly on a ubuntu lxc container but not on a arch qemu vm.

When manually starting with `vncserver :<anynumber>` including number 77 it runs fine.

Can this possibly be because I'm running on a proxmox host, which has an integrated noVNC running? The ubuntu lxc container didn't use noVNC for it's console.

**Comment by CendioOssman** [comment]
The crash was fixed in 4a4453fc69cf56f9991a13a62023969dcf5b8a4f, but that is not the core problem.

The issue is that your Xvnc terminates right away. I'm not sure why it works when you start it manually, because the issue is that the `xstartup` is incorrect. There should not be a `&` at the end of the `startxfce4` line. Please remove that and you should be fine. :)

**Comment by GotekSC** [comment]
It didn't fix it though.

Wether I start startxfce with `exec startxfce4` `dbus-launch /usr/bin/startxfce4` or `dbus-launch /usr/bin/startxfce4 &` makes no difference. Manuall starting works, but through systemd does not.

**Comment by GotekSC** [comment]
I spun up a arch lxc container from the linuxcontainers.org image, and there it works with `dbus-launch /usr/bin/startxfce4` but not `exec startxfce4` didn't test with a trailing &.

I'm not familiar enough with the matter to say wether qemu/proxmox is playing a role here.
