### ISSUE TITLE
keyboard grab not released on secondary monitors on macOS

### ISSUE THREAD

**Issue by qijialiu** [TigerVNC/tigervnc#931]
TigerVNC Viewer 64-bit v1.10.1
macOS  Catalina version 10.15.2

I have two monitors. With VNC viewer running on one of the monitors in full-screen mode and taking system keys directly to server.

When my mouse goes to the other monitor without VNC, the mouse clip works there just instantaneously, but the focus remains at the VNC viewer, as any keyboard input will be directed into the VNC viewer.

In another thread below, a similar issue (on ubuntu but not mentioned on macOS) was resolved. But I'm still having the issue with v1.10.1.
https://github.com/TigerVNC/tigervnc/issues/447

**Comment by CendioOssman** [comment]
I can reproduce this here as well. Not sure what the issue is right now.

Unfortunately #447 was a bit specific to how X11 behaves, so it's not surprising that it didn't have any effect on macOS.

**Comment by CendioOssman** [comment]
Hmm.. This worked fine when testing on macOS 11. Perhaps it was a OS bug rather than something in TigerVNC?

@qijialiu, are you still seeing this problem?

**Comment by qijialiu** [comment]
Pierre,

I'm still with 10.57. Will check about the issue after updating to 11.

Thanks for updating. It sounds good if the issue can be resolved by new macOS.

Thanks,
Qijia
________________________________

**Comment by CendioOssman** [comment]
This should be fixed by 72e94ca93d3ada8fb7f518fa65644d2bc172bd4b, which is also in the new 1.12.0 release.

**Comment by williamsjoblom** [comment]
Despite the alleged fix in 72e94ca I can still reproduce the issue on macOS 12.0.1.

I have tried the following build variations with seemingly identical broken behavior:
- The TigerVNC 1.12.0 release build
- HEAD of the master branch built with FLTK 1.3.7.
- At the alleged fix (72e94ca) with FLTK 1.3.7 and 1.3.5.
- The commit before the alleged fix with FLTK 1.3.7 and 1.3.5.

So, as far as I can tell, this fix externally looks like a NOOP, so we should probably reopen this issue @CendioOssman. Worth noting is that I can only reproduce the issue with vncviewer full-screened on the *primary* monitor (applies to all builds above).

**Comment by samhed** [comment]
Seems like a macOS bug of some sorts, debug prints in FLTK show that the NSWindow isn't getting the `windowDidBecomeKey` or `windowDidResignKey` notifications when in fullscreen on the primary monitor. Those are the notifications meant to generate FLTK's focus events.
